# Generated by Django 3.1.2 on 2021-05-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongName',
            new_name='Song',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
