# Generated by Django 3.1.2 on 2021-05-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210517_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recording_date', models.DateField()),
                ('personnel', models.TextField()),
                ('notes', models.TextField()),
                ('song_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.song')),
            ],
        ),
    ]
