# Generated by Django 3.1.2 on 2021-05-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='recording_date',
            field=models.CharField(max_length=200),
        ),
    ]
