# Generated by Django 3.1.2 on 2021-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210517_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.TextField()),
                ('personnel', models.TextField()),
                ('album_releases', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='song_name',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
