# Generated by Django 3.1.2 on 2021-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_form', models.CharField(max_length=255)),
            ],
        ),
    ]
