# Generated by Django 3.1.2 on 2021-05-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_songform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.key')),
                ('song_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.songform')),
            ],
        ),
    ]
