# Generated by Django 3.1.2 on 2021-05-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='album_releases',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='personnel',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='songform',
            name='song_form',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('transcription_pdf', models.FileField(blank=True, upload_to='media/')),
                ('youtube_link', models.URLField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.session')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.song')),
            ],
        ),
    ]
