# Generated by Django 3.1.2 on 2021-05-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210528_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.key'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.songform'),
        ),
        migrations.AlterField(
            model_name='version',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.session'),
        ),
        migrations.AlterField(
            model_name='version',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.song'),
        ),
        migrations.AlterField(
            model_name='version',
            name='transcription_pdf',
            field=models.FileField(blank=True, upload_to='transcriptions_pdf'),
        ),
    ]
