# Generated by Django 3.1.2 on 2021-06-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210528_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='midi_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
