# Generated by Django 3.1.2 on 2021-06-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210602_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='midi_file',
        ),
    ]
