# Generated by Django 3.1.2 on 2021-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_version_midi_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='sibelius_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
