# Generated by Django 3.2.4 on 2021-06-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210602_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='releases',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='version',
            name='session_song_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.song'),
        ),
    ]
