# Generated by Django 3.2.4 on 2021-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210621_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='version',
            name='releases',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
