# Generated by Django 3.2.4 on 2021-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210621_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='sound_file',
            field=models.FileField(blank=True, upload_to='sound_files'),
        ),
    ]
